apiVersion: apps/v1
kind: Deployment
metadata:
  name: prerender
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prerender
  template:
    metadata:
      labels:
        app: prerender
    spec:
      containers:
        - name: prerender
          image: vhcns5/prerender:6a46adbe3efbb774c4f210e5ff918ea793d9ec9d
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              value: "4000"
            - name: REDIS_URL
              value: redis://:local-dev-redis@redis-master.redis.svc.cluster.local:6379
