apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-a-test
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-a-test
  template:
    metadata:
      labels:
        app: app-a-test
    spec:
      containers:
        - name: app-a-test
          image: vhcns5/app-a:ce22fa1ad632f1661b0cd36058b762b6701c5263
          ports:
            - containerPort: 3000
