apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-a
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-a
  template:
    metadata:
      labels:
        app: app-a
    spec:
      containers:
        - name: app-a
          image: vhcns5/app-a:6a46adbe3efbb774c4f210e5ff918ea793d9ec9d
          ports:
            - containerPort: 3000
