apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-a-test
  namespace: my-test-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-a-test
  template:
    metadata:
      labels:
        app: app-a-test
    spec:
      containers:
        - name: app-a-test
          image: registry.polymorph.co.kr/app-a:45a73763ffd52042d19a9b459068ab2dad8c8d50
          ports:
            - containerPort: 3000
