apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-test-app-a-ingress
  namespace: my-test-apps
spec:
  ingressClassName: traefik
  rules:
    - host: app-a.polymorph.co.kr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-a-test-svc
                port:
                  number: 80
